# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('pwd', models.CharField(max_length=60)),
                ('nicheng', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('updtime', models.DateTimeField(blank=True, null=True)),
                ('role', models.IntegerField(default=1)),
                ('msgnum', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('realname', models.CharField(max_length=60)),
                ('idnumber', models.CharField(max_length=60, unique=True)),
                ('telnumber', models.IntegerField(unique=True)),
                ('qq', models.CharField(blank=True, max_length=60, null=True)),
                ('biming', models.CharField(max_length=60, unique=True)),
                ('idimage', models.CharField(max_length=60)),
                ('idperson', models.CharField(max_length=60)),
                ('appexplain', models.CharField(max_length=255)),
                ('updtime', models.DateTimeField()),
                ('createtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'writers',
                'managed': False,
            },
        ),
    ]
